### ISSUE TITLE
Feilaktig "For mange påmeldte" melding

### ISSUE THREAD

**Issue by arnemahl** [iterateno/itercage#5]
De siste gangene jeg har meldt meg på har jeg fått opp "For mange påmeldte. Kontakt truls@iterate.no dersom du vil være med", kode [her](https://github.com/iterate/itercage/blob/master/client/itercage.js#L60).

Det er ikke for mange påmeldte, men jeg ser at meldingen vises uavhengig av hva som går galt når man legger seg til: `Meteor.call('addAttendee', name, function(error) {...`.

**Comment by KBnkiGi8OsAjTTXpEzGpOuyVFd9L6k9NVk1tTJj** [comment]
:-( Reproduserbar?

**Comment by kDZOhjEZ1VAqGyC7RAKzVpIi2qeg5pQP5U4gyBE** [comment]
Det er en feature...
